# Generated by Django 3.2.3 on 2021-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210621_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/Cover.jpg', null=True, upload_to='profiles/'),
        ),
    ]
